services:
  - type: web
    name: laravel-backend
    runtime: docker
    region: singapore
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true            # 🔐 Auto-generate a random key
      - key: APP_URL
        value: https://bt-xxxx.onrender.com

      # SQLite Setup
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/database/database.sqlite

      # Mail setup
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: your_email@gmail.com
      - key: MAIL_PASSWORD
        value: your_gmail_app_password
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: your_email@gmail.com
      - key: MAIL_FROM_NAME
        value: "User Product App"

      # CORS whitelist
      - key: FRONTEND_URL
        value: https://your-frontend.vercel.app
